In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('C:/Users/DINESH/kaggle nlp/train.csv')
test = pd.read_csv('C:/Users/DINESH/kaggle nlp/test.csv')
sub = pd.read_csv('C:/Users/DINESH/kaggle nlp/sample_submission.csv')


In [3]:
sample_submission = pd.read_csv('C:/Users/DINESH/kaggle nlp/sample_submission.csv')

In [4]:
train.shape

(7613, 5)

In [5]:
test.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [6]:
sub.head()

id  target
0   0       1
1   2       1
2   3       1
3   9       1
4  11       1

In [7]:
import re
import string
import nltk
from nltk.corpus import stopwords

In [8]:
def rmv_spl_text(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

# Applying the cleaning function to both test and training datasets
train['text'] = train['text'].apply(lambda x: rmv_spl_text(x))
test['text'] = test['text'].apply(lambda x: rmv_spl_text(x))

# Let's take a look at the updated text
train['text'].head()

0    our deeds are the reason of this earthquake ma...
1                forest fire near la ronge sask canada
2    all residents asked to shelter in place are be...
3     people receive wildfires evacuation orders in...
4    just got sent this photo from ruby alaska as s...
Name: text, dtype: object

In [15]:

# sklearn 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import model_selection
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score
from sklearn import preprocessing, decomposition, model_selection, metrics, pipeline
from sklearn.model_selection import GridSearchCV,StratifiedKFold,RandomizedSearchCV

In [10]:
# Tokenizing the training and the test set
toknzr = nltk.tokenize.RegexpTokenizer(r'\w+')
train['text'] = train['text'].apply(lambda x: toknzr.tokenize(x))
test['text'] = test['text'].apply(lambda x: toknzr.tokenize(x))
train['text'].head()

0    [our, deeds, are, the, reason, of, this, earth...
1        [forest, fire, near, la, ronge, sask, canada]
2    [all, residents, asked, to, shelter, in, place...
3    [people, receive, wildfires, evacuation, order...
4    [just, got, sent, this, photo, from, ruby, ala...
Name: text, dtype: object

In [11]:
def rmv_stopwords(text):
    words = [w for w in text if w not in stopwords.words('english')]
    return words


train['text'] = train['text'].apply(lambda x : rmv_stopwords(x))
test['text'] = test['text'].apply(lambda x : rmv_stopwords(x))
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  [deeds, reason, earthquake, may, allah, forgiv...   
1   4     NaN      NaN      [forest, fire, near, la, ronge, sask, canada]   
2   5     NaN      NaN  [residents, asked, shelter, place, notified, o...   
3   6     NaN      NaN  [people, receive, wildfires, evacuation, order...   
4   7     NaN      NaN  [got, sent, photo, ruby, alaska, smoke, wildfi...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [12]:
def combine_text(list_of_text):
    '''Takes a list of text and combines them into one large chunk of text.'''
    combined_text = ' '.join(list_of_text)
    return combined_text

train['text'] = train['text'].apply(lambda x : combine_text(x))
test['text'] = test['text'].apply(lambda x : combine_text(x))
train['text']
train.head()

id keyword location                                               text  \
0   1     NaN      NaN       deeds reason earthquake may allah forgive us   
1   4     NaN      NaN              forest fire near la ronge sask canada   
2   5     NaN      NaN  residents asked shelter place notified officer...   
3   6     NaN      NaN  people receive wildfires evacuation orders cal...   
4   7     NaN      NaN  got sent photo ruby alaska smoke wildfires pou...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [16]:
count_vectorizer = CountVectorizer()
train_vectors = count_vectorizer.fit_transform(train['text'])
test_vectors = count_vectorizer.transform(test["text"])

## Keeping only non-zero elements to preserve space 
print(train_vectors[0].todense())

[[0 0 0 ... 0 0 0]]


In [18]:
tfidf = TfidfVectorizer(min_df=2, max_df=0.5, ngram_range=(1, 2))
train_tfidf = tfidf.fit_transform(train['text'])
test_tfidf = tfidf.transform(test["text"])

In [17]:
# Fitting a simple Logistic Regression on Counts
clf = LogisticRegression(C=1.0)
scores = model_selection.cross_val_score(clf, train_vectors, train["target"], cv=5, scoring="f1")
scores

C:\Users\DINESH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.59865255, 0.50301464, 0.57118787, 0.5669145 , 0.68888889])

In [19]:
clf.fit(train_vectors, train["target"])

C:\Users\DINESH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
clf_tfidf = LogisticRegression(C=1.0)
scores = model_selection.cross_val_score(clf_tfidf, train_tfidf, train["target"], cv=5, scoring="f1")
scores

C:\Users\DINESH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.57258065, 0.49626866, 0.54277829, 0.46618106, 0.64768683])

In [21]:
# Fitting a simple Naive Bayes on Counts
clf_NB = MultinomialNB()
scores = model_selection.cross_val_score(clf_NB, train_vectors, train["target"], cv=5, scoring="f1")
scores

array([0.63324979, 0.60688666, 0.68718683, 0.64341085, 0.72505092])

In [22]:
clf_NB.fit(train_vectors, train["target"])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
# Fitting a simple Naive Bayes on TFIDF
clf_NB_TFIDF = MultinomialNB()
scores = model_selection.cross_val_score(clf_NB_TFIDF, train_tfidf, train["target"], cv=10, scoring="f1")
scores

array([0.62786596, 0.49609375, 0.58519793, 0.45644599, 0.58684654,
       0.55341506, 0.61458333, 0.56380952, 0.71268058, 0.74645669])

In [24]:
clf_NB_TFIDF.fit(train_tfidf, train["target"])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [37]:

sample_submission["target"] = clf_NB_TFIDF.predict(test_vectors)
sample_submission.to_csv('C:/Users/DINESH/kaggle nlp/sample_submission.csv',index=False)

In [38]:
 sample_submission.head()

id  target
0   0       1
1   2       0
2   3       1
3   9       1
4  11       1